// <auto-generated />
using System;
using LVTNWEBGIAYDEP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LVTNWEBGIAYDEP.Migrations
{
    [DbContext(typeof(DBGiayDepContext))]
    [Migration("20260325104052_InitSqlite")]
    partial class InitSqlite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.ChiTietDonHang", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("maSP");

                    b.Property<int>("iDDonHang")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iDDonHang");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soLuong");

                    b.HasKey("MaSp", "iDDonHang");

                    b.HasIndex("iDDonHang");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.DonHang", b =>
                {
                    b.Property<int>("iDDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("diaChi");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("taiKhoan");

                    b.Property<DateTime?>("ngayLapDon")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayLapDon");

                    b.Property<string>("noiDungHuy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("noiDungHuy");

                    b.Property<string>("thanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("thanhToan");

                    b.Property<string>("trangThai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("trangThai");

                    b.HasKey("iDDonHang");

                    b.HasIndex("TaiKhoan");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.LienHe", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("noiDung");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("taiKhoan");

                    b.Property<string>("noiDungPhanHoi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("noiDungPhanHoi");

                    b.Property<string>("trangThai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("trangThai");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoan");

                    b.ToTable("LienHe", (string)null);
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("maLoai");

                    b.Property<int?>("MaTh")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maTH");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenLoai");

                    b.HasKey("MaLoai");

                    b.HasIndex("MaTh");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.SanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("maSP");

                    b.Property<int?>("GiaBan")
                        .HasColumnType("INTEGER")
                        .HasColumnName("giaBan");

                    b.Property<int?>("HangTonKho")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hangTonKho");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("hinhAnh");

                    b.Property<int?>("KichCo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kichCo");

                    b.Property<int>("MaLoai")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maLoai");

                    b.Property<string>("MoTa")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("moTa");

                    b.Property<DateTime?>("NgayThemSP")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayThemSP");

                    b.Property<string>("TenSp")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenSP");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("trangThai");

                    b.HasKey("MaSp")
                        .HasName("PK_SanPham_1");

                    b.HasIndex("MaLoai");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TaiKhoan1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("taiKhoan");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("hoTen");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("matKhau");

                    b.Property<string>("phanQuyen")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phanQuyen");

                    b.Property<string>("trangThai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("trangThai");

                    b.HasKey("TaiKhoan1");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.ThuongHieu", b =>
                {
                    b.Property<int>("MaTh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaTh");

                    b.Property<string>("TenTh")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenTH");

                    b.HasKey("MaTh");

                    b.ToTable("ThuongHieu", (string)null);
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("LVTNWEBGIAYDEP.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietDonHang_SanPham");

                    b.HasOne("LVTNWEBGIAYDEP.Models.DonHang", "iDDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("iDDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietDonHang_DonHang");

                    b.Navigation("MaSpNavigation");

                    b.Navigation("iDDonHangNavigation");
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.DonHang", b =>
                {
                    b.HasOne("LVTNWEBGIAYDEP.Models.TaiKhoan", "TaiKhoanNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("TaiKhoan")
                        .HasConstraintName("FK_DonHang_TaiKhoan");

                    b.Navigation("TaiKhoanNavigation");
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.LienHe", b =>
                {
                    b.HasOne("LVTNWEBGIAYDEP.Models.TaiKhoan", "TaiKhoanNavigation")
                        .WithMany("LienHes")
                        .HasForeignKey("TaiKhoan")
                        .IsRequired()
                        .HasConstraintName("FK_LienHe_TaiKhoan");

                    b.Navigation("TaiKhoanNavigation");
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.LoaiSanPham", b =>
                {
                    b.HasOne("LVTNWEBGIAYDEP.Models.ThuongHieu", "MaThNavigation")
                        .WithMany("LoaiSanPhams")
                        .HasForeignKey("MaTh")
                        .HasConstraintName("FK_LoaiSanPham_ThuongHieu");

                    b.Navigation("MaThNavigation");
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.SanPham", b =>
                {
                    b.HasOne("LVTNWEBGIAYDEP.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_LoaiSanPham");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.TaiKhoan", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("LienHes");
                });

            modelBuilder.Entity("LVTNWEBGIAYDEP.Models.ThuongHieu", b =>
                {
                    b.Navigation("LoaiSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
